jobs:
 - reduce_sectors:
    reduce:
     - {topologies: [mercedes], sectors: [63], r: 12, s: 0}


    select_integrals:
      select_mandatory_list:
        - [mercedes, target]


    preferred_masters: preferred
    integral_ordering: 5


    run_initiate: true
    run_triangular: true
    run_back_substitution: true


 - kira2math:
    target:
     - [mercedes, target]