jobs:
 - reduce_sectors:
    reduce:
     - {topologies: [bhabha2npb], sectors: [3], r: 5, s: 0}


    select_integrals:
      select_mandatory_list:
        - [bhabha2npb, target]


    preferred_masters: preferred
    integral_ordering: 5


    run_initiate: true
    run_triangular: true
    run_back_substitution: true


 - kira2math:
    target:
     - [bhabha2npb, target]