kinematics:
  incoming_momenta: [p1, p2, p3, bhabha2npbAuxLeg]
  outgoing_momenta: []
  momentum_conservation: [bhabha2npbAuxLeg, -p1 - p2 - p3]
  kinematic_invariants:
    - [eta, 2]
  scalarproduct_rules:
    - [[p1,p1], 1]
    - [[p1,p2], 3]
    - [[p1,p3], -3/2]
    - [[p2,p2], 1]
    - [[p2,p3], -5/2]
    - [[p3,p3], 1]