integralfamilies:
  - name: "mercedes"
    loop_momenta: [l1, l2, l3]
    top_level_sectors: [511]
    propagators:
      - [ "-eta + l1^2", 0 ]
      - [ "(l1 + p1)^2", 0 ]
      - [ "l2^2", 0 ]
      - [ "(l2 + p2)^2", 0 ]
      - [ "l3^2", 0 ]
      - [ "(l3 - p1 - p2)^2", 0 ]
      - [ "(-l1 + l2 - p1)^2", 0 ]
      - [ "(-l2 + l3 - p2)^2", 0 ]
      - [ "(l1 - l3 + p1 + p2)^2", 0 ]
      - [ "(l1 + p2)^2", 0 ]
      - [ "(l2 - p1 - p2)^2", 0 ]
      - [ "(l3 + p1)^2", 0 ]
    cut_propagators: []