kinematics:
  incoming_momenta: [l1, bhabha2vboxAuxLeg]
  outgoing_momenta: []
  momentum_conservation: [bhabha2vboxAuxLeg, -l1]
  kinematic_invariants:
    - [eta, 2]
  scalarproduct_rules:
    - [[l1,l1], -1]